/**
 * Auto-generated by scripts/generate-coverage-stats.mjs
 * Last generated: 2026-04-14
 * Source: scripts/validate/reports/validation-latest.json
 *
 * DO NOT EDIT MANUALLY — run: npm run generate:coverage
 */

export const COVERAGE_STATS: Record<string, { label: string; present: number; total: number }> = {
  'council_tax': { label: 'Council tax rates', present: 317, total: 317 },
  'budget': { label: 'Service budgets', present: 317, total: 317 },
  'chief_executive_salary': { label: 'CEO salary', present: 317, total: 317 },
  'councillor_basic_allowance': { label: 'Councillor basic allowance', present: 317, total: 317 },
  'total_allowances_cost': { label: 'Total allowances cost', present: 306, total: 317 },
  'councillor_allowances_detail': { label: 'Councillor allowances detail', present: 317, total: 317 },
  'salary_bands': { label: 'Salary bands', present: 317, total: 317 },
  'staff_fte': { label: 'Staff headcount (FTE)', present: 317, total: 317 },
  'top_suppliers': { label: 'Top suppliers', present: 317, total: 317 },
  'grant_payments': { label: 'Grant payments', present: 154, total: 317 },
  'service_spending': { label: 'Service spending detail', present: 317, total: 317 },
  'performance_kpis': { label: 'Performance KPIs', present: 317, total: 317 },
  'waste_destinations': { label: 'Waste destinations', present: 153, total: 153 },
  'documents': { label: 'Official documents', present: 317, total: 317 },
  'sources': { label: 'Source links', present: 317, total: 317 },
  'cabinet': { label: 'Cabinet members', present: 317, total: 317 },
  'budget_gap': { label: 'Budget gap / savings', present: 317, total: 317 },
  'savings_target': { label: 'Savings target', present: 317, total: 317 },
};

export const VALIDATION_SUMMARY = {
  errors: 1,
  warnings: 557,
  info: 15,
  regressions: 0,
  totalChecks: 32872,
  totalCouncils: 317,
  parityAverage: 98.4,
  timestamp: '2026-04-14',
};
