/**
 * Auto-generated by scripts/generate-coverage-stats.mjs
 * Last generated: 2026-05-01
 * Source: scripts/validate/reports/validation-latest.json
 *
 * DO NOT EDIT MANUALLY — run: npm run generate:coverage
 */

export const COVERAGE_STATS: Record<string, { label: string; present: number; total: number }> = {
  'council_tax': { label: 'Council tax rates', present: 316, total: 316 },
  'budget': { label: 'Service budgets', present: 316, total: 316 },
  'chief_executive_salary': { label: 'CEO salary', present: 277, total: 316 },
  'councillor_basic_allowance': { label: 'Councillor basic allowance', present: 255, total: 316 },
  'total_allowances_cost': { label: 'Total allowances cost', present: 218, total: 316 },
  'councillor_allowances_detail': { label: 'Councillor allowances detail', present: 153, total: 316 },
  'salary_bands': { label: 'Salary bands', present: 156, total: 316 },
  'staff_fte': { label: 'Staff headcount (FTE)', present: 204, total: 316 },
  'top_suppliers': { label: 'Top suppliers', present: 156, total: 316 },
  'grant_payments': { label: 'Grant payments', present: 153, total: 316 },
  'service_spending': { label: 'Service spending detail', present: 157, total: 316 },
  'performance_kpis': { label: 'Performance KPIs', present: 155, total: 316 },
  'waste_destinations': { label: 'Waste destinations', present: 40, total: 152 },
  'documents': { label: 'Official documents', present: 248, total: 316 },
  'sources': { label: 'Source links', present: 316, total: 316 },
  'cabinet': { label: 'Cabinet members', present: 179, total: 316 },
  'budget_gap': { label: 'Budget gap / savings', present: 216, total: 316 },
  'savings_target': { label: 'Savings target', present: 216, total: 316 },
};

export const VALIDATION_SUMMARY = {
  errors: 0,
  warnings: 2506,
  info: 9,
  regressions: 0,
  totalChecks: 54157,
  totalCouncils: 316,
  parityAverage: 81.7,
  timestamp: '2026-05-01',
};
