/**
 * Auto-generated by scripts/generate-coverage-stats.mjs
 * Last generated: 2026-04-23
 * Source: scripts/validate/reports/validation-latest.json
 *
 * DO NOT EDIT MANUALLY — run: npm run generate:coverage
 */

export const COVERAGE_STATS: Record<string, { label: string; present: number; total: number }> = {
<<<<<<< HEAD
  'council_tax': { label: 'Council tax rates', present: 316, total: 316 },
  'budget': { label: 'Service budgets', present: 316, total: 316 },
  'chief_executive_salary': { label: 'CEO salary', present: 309, total: 316 },
  'councillor_basic_allowance': { label: 'Councillor basic allowance', present: 316, total: 316 },
  'total_allowances_cost': { label: 'Total allowances cost', present: 300, total: 316 },
  'councillor_allowances_detail': { label: 'Councillor allowances detail', present: 301, total: 316 },
  'salary_bands': { label: 'Salary bands', present: 301, total: 316 },
  'staff_fte': { label: 'Staff headcount (FTE)', present: 299, total: 316 },
  'top_suppliers': { label: 'Top suppliers', present: 301, total: 316 },
  'grant_payments': { label: 'Grant payments', present: 298, total: 316 },
  'service_spending': { label: 'Service spending detail', present: 301, total: 316 },
  'performance_kpis': { label: 'Performance KPIs', present: 301, total: 316 },
  'waste_destinations': { label: 'Waste destinations', present: 138, total: 152 },
  'documents': { label: 'Official documents', present: 316, total: 316 },
  'sources': { label: 'Source links', present: 316, total: 316 },
  'cabinet': { label: 'Cabinet members', present: 316, total: 316 },
  'budget_gap': { label: 'Budget gap / savings', present: 302, total: 316 },
  'savings_target': { label: 'Savings target', present: 302, total: 316 },
=======
  'council_tax': { label: 'Council tax rates', present: 315, total: 315 },
  'budget': { label: 'Service budgets', present: 315, total: 315 },
  'chief_executive_salary': { label: 'CEO salary', present: 307, total: 315 },
  'councillor_basic_allowance': { label: 'Councillor basic allowance', present: 315, total: 315 },
  'total_allowances_cost': { label: 'Total allowances cost', present: 299, total: 315 },
  'councillor_allowances_detail': { label: 'Councillor allowances detail', present: 300, total: 315 },
  'salary_bands': { label: 'Salary bands', present: 300, total: 315 },
  'staff_fte': { label: 'Staff headcount (FTE)', present: 298, total: 315 },
  'top_suppliers': { label: 'Top suppliers', present: 300, total: 315 },
  'grant_payments': { label: 'Grant payments', present: 297, total: 315 },
  'service_spending': { label: 'Service spending detail', present: 300, total: 315 },
  'performance_kpis': { label: 'Performance KPIs', present: 300, total: 315 },
  'waste_destinations': { label: 'Waste destinations', present: 137, total: 151 },
  'documents': { label: 'Official documents', present: 315, total: 315 },
  'sources': { label: 'Source links', present: 315, total: 315 },
  'cabinet': { label: 'Cabinet members', present: 315, total: 315 },
  'budget_gap': { label: 'Budget gap / savings', present: 301, total: 315 },
  'savings_target': { label: 'Savings target', present: 301, total: 315 },
>>>>>>> d69819d (feat(rollout): Batch-7 — Nottinghamshire, Staffordshire, Wiltshire, Newcastle, Croydon)
};

export const VALIDATION_SUMMARY = {
  errors: 0,
<<<<<<< HEAD
  warnings: 3399,
  info: 10,
  regressions: 0,
  totalChecks: 57437,
  totalCouncils: 316,
  parityAverage: 98.3,
=======
  warnings: 3386,
  info: 12,
  regressions: 0,
  totalChecks: 57246,
  totalCouncils: 315,
  parityAverage: 98.2,
>>>>>>> d69819d (feat(rollout): Batch-7 — Nottinghamshire, Staffordshire, Wiltshire, Newcastle, Croydon)
  timestamp: '2026-04-23',
};
