/**
 * Auto-generated by scripts/generate-proven-fields.mjs
 * Source: scripts/validate/reports/proof-latest.json
 *
 * DO NOT EDIT MANUALLY — run: npm run generate:proven
 *
 * The render gate's source of truth (NORTH-STAR / PIPELINE.md Stage 5).
 * PROVEN_FIELDS[councilSlug] = the set of field paths the proof engine could
 * independently re-derive from evidence. A value renders ONLY if it is in this
 * set (default-deny): unproven numbers are hidden, never shown wrong.
 */

export const PROVEN_FIELDS: Record<string, string[]> = {
  "cambridgeshire": [
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "derbyshire": [
    "detailed.chief_executive",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "devon": [
    "detailed.reserves"
  ],
  "east-sussex": [
    "detailed.chief_executive",
    "detailed.reserves"
  ],
  "essex": [
    "detailed.reserves"
  ],
  "gloucestershire": [
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "hampshire": [
    "detailed.chief_executive_salary"
  ],
  "hertfordshire": [
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "kent": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.band_d_2025",
    "detailed.budget_gap",
    "detailed.council_tax_base",
    "detailed.council_tax_increase_percent",
    "detailed.council_tax_requirement",
    "detailed.reserves",
    "detailed.revenue_budget",
    "detailed.savings_target"
  ],
  "lancashire": [
    "detailed.chief_executive"
  ],
  "leicestershire": [
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "lincolnshire": [
    "detailed.chief_executive",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "norfolk": [
    "detailed.cabinet",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.savings_target"
  ],
  "nottinghamshire": [
    "detailed.chief_executive_salary"
  ],
  "oxfordshire": [
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.reserves"
  ],
  "staffordshire": [
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ],
  "suffolk": [
    "detailed.chief_executive",
    "detailed.reserves"
  ],
  "surrey": [
    "detailed.chief_executive",
    "detailed.council_tax_increase_percent"
  ],
  "west-sussex": [
    "detailed.cabinet",
    "detailed.chief_executive",
    "detailed.council_leader",
    "detailed.reserves"
  ],
  "worcestershire": [
    "detailed.reserves"
  ],
  "adur": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "amber-valley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.councillor_basic_allowance",
    "detailed.leader_allowance",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "arun": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.councillor_basic_allowance",
    "detailed.leader_allowance",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "ashfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "ashford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.total_allowances_cost"
  ],
  "babergh": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.total_allowances_cost"
  ],
  "basildon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.chief_executive",
    "detailed.reserves",
    "detailed.savings_target"
  ],
  "basingstoke-and-deane": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.total_allowances_cost"
  ],
  "bassetlaw": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "blaby": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "bolsover": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "boston": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.total_allowances_cost"
  ],
  "braintree": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "breckland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "brentwood": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "broadland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.councillor_basic_allowance",
    "detailed.leader_allowance",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "bromsgrove": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.councillor_basic_allowance",
    "detailed.leader_allowance",
    "detailed.savings_target",
    "detailed.total_allowances_cost"
  ],
  "broxbourne": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.total_allowances_cost"
  ],
  "broxtowe": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "burnley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "cambridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "cannock-chase": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "canterbury": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "castle-point": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "charnwood": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "chelmsford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "cheltenham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "cherwell": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "chesterfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "chichester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "chorley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "colchester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "cotswold": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "crawley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "dacorum": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "dartford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "derbyshire-dales": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "dover": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-cambridgeshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-devon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-hampshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "east-hertfordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-lindsey": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-staffordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "east-suffolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "eastbourne": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "eastleigh": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "elmbridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "epping-forest": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "epsom-and-ewell": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "erewash": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "exeter": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "fareham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "fenland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "folkestone-and-hythe": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "forest-of-dean": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "fylde": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "gedling": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "gloucester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "gosport": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "gravesham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "great-yarmouth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "guildford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "harborough": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "harlow": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hart": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hastings": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "havant": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "hertsmere": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "high-peak": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "hinckley-and-bosworth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "horsham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "huntingdonshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hyndburn": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "ipswich": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "kings-lynn-and-west-norfolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lancaster": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lewes": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lichfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lincoln": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "maidstone": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "maldon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "malvern-hills": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "mansfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "melton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "mid-devon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "mid-suffolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "mid-sussex": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "mole-valley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "new-forest": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "newark-and-sherwood": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "newcastle-under-lyme": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-devon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "north-east-derbyshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-hertfordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-norfolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "north-warwickshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-west-leicestershire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "norwich": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "nuneaton-and-bedworth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "oadby-and-wigston": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "oxford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "pendle": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "preston": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "redditch": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "reigate-and-banstead": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "ribble-valley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rochford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rossendale": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rother": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rugby": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "runnymede": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "rushcliffe": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rushmoor": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "sevenoaks": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "south-cambridgeshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-derbyshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-hams": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-holland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-kesteven": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "south-norfolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-oxfordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "south-ribble": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-staffordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "spelthorne": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive"
  ],
  "st-albans": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "stafford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "staffordshire-moorlands": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "stevenage": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "stratford-on-avon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "stroud": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "surrey-heath": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "swale": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tamworth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tandridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "teignbridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tendring": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "test-valley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tewkesbury": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "thanet": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "three-rivers": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "tonbridge-and-malling": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "torridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tunbridge-wells": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "uttlesford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "vale-of-white-horse": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "warwick": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "watford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "waverley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wealden": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "welwyn-hatfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "west-devon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "west-lancashire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "west-lindsey": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "west-oxfordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "west-suffolk": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "winchester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "woking": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "worcester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "worthing": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wychavon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wyre": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wyre-forest": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "barnsley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ],
  "birmingham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "bolton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "bradford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.capital_programme",
    "detailed.chief_executive_salary",
    "detailed.council_tax_requirement",
    "detailed.councillor_allowances_detail",
    "detailed.councillor_basic_allowance",
    "detailed.reserves",
    "detailed.salary_bands",
    "detailed.savings_target",
    "detailed.total_allowances_cost",
    "detailed.total_councillors",
    "history.reserves.2023-24"
  ],
  "bury": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "calderdale": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "coventry": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.reserves"
  ],
  "doncaster": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.total_allowances_cost"
  ],
  "dudley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.council_leader"
  ],
  "gateshead": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "kirklees": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "knowsley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "leeds": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "liverpool": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "manchester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "newcastle-upon-tyne": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive"
  ],
  "north-tyneside": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "oldham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.council_leader"
  ],
  "rochdale": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "rotherham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "salford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.council_leader",
    "detailed.reserves"
  ],
  "sandwell": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader"
  ],
  "sefton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.reserves",
    "detailed.total_allowances_cost"
  ],
  "sheffield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "solihull": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "south-tyneside": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "st-helens": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "stockport": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.council_leader"
  ],
  "sunderland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "tameside": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "trafford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wakefield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.budget_gap",
    "detailed.council_leader",
    "detailed.total_allowances_cost"
  ],
  "walsall": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "wigan": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "wirral": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "wolverhampton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader",
    "detailed.total_allowances_cost"
  ],
  "bath-and-north-east-somerset": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "bedford": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "blackburn-with-darwen": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "blackpool": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "bournemouth-christchurch-and-poole": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "bracknell-forest": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "brighton-and-hove": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "bristol": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "buckinghamshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "central-bedfordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "cheshire-east": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "cheshire-west-and-chester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "cornwall": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ],
  "cumberland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "darlington": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "derby": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "dorset-ua": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "durham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "east-riding-of-yorkshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "halton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hartlepool": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "herefordshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "isle-of-wight": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "isles-of-scilly": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "kingston-upon-hull": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "leicester": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "luton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "medway-towns": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "middlesbrough": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "milton-keynes": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-east-lincolnshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-lincolnshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-northamptonshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-somerset": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "north-yorkshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ],
  "northumberland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "nottingham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "peterborough": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "plymouth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.council_leader"
  ],
  "portsmouth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "reading": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "redcar-and-cleveland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "rutland": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "shropshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "slough": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "somerset": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "south-gloucestershire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "southampton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "southend-on-sea": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "stockton-on-tees": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "stoke-on-trent": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "swindon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "telford-and-wrekin": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "thurrock": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "torbay": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "warrington": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "west-berkshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "west-northamptonshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "westmorland-and-furness": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wiltshire": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive"
  ],
  "windsor-and-maidenhead": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "wokingham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "york": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "barking-and-dagenham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "barnet": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "bexley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "brent": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "bromley": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "camden": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.cabinet",
    "detailed.councillor_basic_allowance",
    "detailed.leader_allowance",
    "detailed.reserves"
  ],
  "city-of-london": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "croydon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ],
  "ealing": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "enfield": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "greenwich": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hackney": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hammersmith-and-fulham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "haringey": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "harrow": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "havering": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive"
  ],
  "hillingdon": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "hounslow": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "islington": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "kensington-and-chelsea": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "kingston-upon-thames": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lambeth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "lewisham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "merton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "newham": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "redbridge": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "richmond-upon-thames": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary"
  ],
  "southwark": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "sutton": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive",
    "detailed.chief_executive_salary"
  ],
  "tower-hamlets": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.reserves"
  ],
  "waltham-forest": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "wandsworth": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026"
  ],
  "westminster": [
    "council_tax.band_d_2021",
    "council_tax.band_d_2022",
    "council_tax.band_d_2023",
    "council_tax.band_d_2024",
    "council_tax.band_d_2025",
    "council_tax.band_d_2026",
    "detailed.chief_executive_salary",
    "detailed.reserves"
  ]
};

export const PROVEN_GENERATED_AT = "2026-06-16T14:41:28.118Z";
